#!/bin/sh

TMP=$(mktemp -d /tmp/clips.XXXX)

trap "rm -r $TMP" EXIT


echo "(defglobal ?*output-path* = $1)" >>$TMP/start.clp
shift
echo "(defglobal ?*requested-functions* = (create$ $@))" >>$TMP/start.clp


cd "$(dirname "$(readlink -f "$0")")"

clips -l $TMP/start.clp -f2 tools/main.clp
