(deffunction call-with-output-file (?path ?function ?rest-arguments)
  (bind ?f (gensym*))
  (open ?path ?f "w")
  (bind ?result (funcall ?function ?f (expand$ ?rest-arguments)))
  (close ?f)
  ?result)
