(deffunction date-compare (?date-1 ?date-2)
  (bind ?date-1-parts (UNNAMED::split-string ?date-1 -separator "-"))
  (bind ?date-2-parts (UNNAMED::split-string ?date-2 -separator "-"))
  (loop-for-count (?i 3)
    (bind ?result (- (string-to-field (nth$ ?i ?date-1-parts))
                     (string-to-field (nth$ ?i ?date-2-parts))))
    (if (<> ?result 0)
     then (return (if (< ?result 0) then -1 else 1))))
  (return 0))
