(deffunction get-process-environments ()
  (bind ?result (create$))
  (bind ?file (gensym*))
  (open "/proc/self/environ" ?file)
  (bind ?environment "")
  (while (<> (bind ?c (get-char ?file)) -1)
    (if (= ?c 0)
     then (bind ?result ?result ?environment)
          (bind ?environment "")
     else (bind ?environment (format nil "%s%c" ?environment ?c))))
  (close ?file)
  ?result)
