(deffunction get-process-arguments ()
  (bind ?result (create$))
  (bind ?file (gensym*))
  (open "/proc/self/cmdline" ?file)
  (bind ?argument "")
  (while (<> (bind ?c (get-char ?file)) -1)
    (if (= ?c 0)
     then (bind ?result ?result ?argument)
          (bind ?argument "")
     else (bind ?argument (format nil "%s%c" ?argument ?c))))
  (close ?file)
  ?result)
