(deffunction load-plain-file (?path)
  (bind ?result "")
  (bind ?file (gensym*))
  (open ?path ?file)
  (while (neq (bind ?line (readline ?file)) EOF)
    (bind ?result (format nil "%s%s" ?result ?line)))
  (close ?file)
  ?result)
