(deffunction load-clips-file (?path)
  (bind ?result (create$))
  (bind ?id (gensym*))
  (open ?path ?id)
  (while (neq (bind ?expression (read ?id)) EOF)
    (bind ?result ?result ?expression))
  (close ?id)
  ?result)
