(deffunction read-binary-file (?path)
  (bind ?result "")
  (bind ?f (gensym*))
  (open ?path ?f)
  (while (neq (bind ?c (get-char ?f)) -1)
    (bind ?result (format nil "%s%c" ?result ?c)))
  (close ?f)
  ?result)
