(deffunction read-plain-file (?path)
  (bind ?result "")
  (bind ?id (gensym*))
  (open ?path ?id)
  (while (neq (bind ?line (readline ?id)) EOF)
    (bind ?result (format nil "%s%s%n" ?result ?line)))
  (close ?id)
  ?result)
