(deffunction read-plain-file (?path)
  (bind ?result "")
  (bind ?f (gensym*))
  (open ?path ?f)
  (while (neq (bind ?line (readline ?f)) EOF)
    (bind ?result (format nil "%s%s%n" ?result ?line)))
  (close ?f)
  ?result)
